name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to checkout when cutting the release."
        required: true
        default: "main"
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      #      - uses: actions/setup-java@v3
      #        with:
      #          distribution: 'temurin'
      #          java-version: 8
      #          cache: 'maven'
      #          check-latest: false
      #          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
      #          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Release
        uses: qcastel/github-actions-maven-release@v1.12.39
        with:
          git-release-bot-name: "Github Actions"
          git-release-bot-email: "actions@github.com"
          release-branch-name: ${{ github.event.inputs.branch }}
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests Dmaven.deploy.skip=true"
          ssh-private-key: ${{ secrets.ACTIONS_PRIVATE_KEY }}
          maven-servers: [{"id": "github", "username": "${env.GITHUB_ACTOR}", "password": "${env.GITHUB_TOKEN}"}]
        env:
          #          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          #          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}

